import { OnDestroy, OnInit } from '@angular/core';
import { SocialService } from '../social.service';
import { ActivityParams } from '../model/ActivityParams';
import { SocialActivity } from '../model/Activity';
import { ActivityPostComponent } from '../activity-post/activity-post.component';
export declare class ActivityListComponent implements OnInit, OnDestroy {
    socialService: SocialService;
    activityPost: ActivityPostComponent;
    postEnable: boolean;
    scroller: HTMLElement | any;
    type: string;
    application: string;
    loader: Function;
    activities: SocialActivity[];
    showLoading: boolean;
    hasMore: boolean;
    params: ActivityParams;
    private _activityChange;
    private _loading;
    constructor(socialService: SocialService);
    ngOnInit(): void;
    ngOnDestroy(): void;
    removeActivityById(id: string): void;
    loadWall(init?: boolean): void;
    doLoadWall(params: any, callback: any): void;
    clearWall(): void;
    private _renderWall;
    activityCreate(params: any): void;
    activityUpdated(activity: SocialActivity): void;
    activityDeleted(activity: SocialActivity): void;
    initScroller(): void;
    scrollToTop(): void;
    initEventScroller(scroller: HTMLElement | any): void;
    removeEventScroller(): void;
    private _scrollBottomListener;
    private _activityPosted;
    private _addActivity;
}
