import { AfterViewInit, ElementRef, EventEmitter, OnDestroy } from '@angular/core';
import { Router } from '@angular/router';
import { CalEvent } from "../utils/model/CalEvent";
import { CalendarDialogDelete } from "../dialog-delete/dialog-delete.component";
import { CalendarEvent } from "../model/CalendarEvent";
export declare class CalendarDialogViewComponent implements AfterViewInit, OnDestroy {
    private router;
    onChange: EventEmitter<{}>;
    modalView: ElementRef;
    viewDeleteModal: CalendarDialogDelete;
    calendarEvent: CalendarEvent;
    calEvent: CalEvent;
    maxHeight: number;
    titleOverlay: boolean;
    private _showModal;
    private _targetEl;
    private _jsEvent;
    private _timer;
    private _scrollTimer;
    private _$modalView;
    private _onChange;
    constructor(router: Router);
    ngAfterViewInit(): void;
    ngOnDestroy(): void;
    editEvent(): void;
    changeEvent(): void;
    viewEvent(event: CalEvent, jsEvent: MouseEvent, target: HTMLElement, onChange: Function): void;
    hide(): void;
    show(): void;
    removeEvent(): void;
    private _preventScrolling;
    private _syncBodyHeight;
    private _initModalView;
    private _destroyModalView;
    private _addScrollUpdatePos;
    private _removeScrollUpdatePos;
    private _scrollUpdatePos;
    private _openModal;
}
