import { ElementRef, OnDestroy, OnInit, TemplateRef } from '@angular/core';
import { Contact } from "../../model/contact";
import { Address } from "../../model/address";
import { GlobalContactService } from "../global-contact.service";
import { NotificationService, UserProfileService } from "inet-core";
import { TranslateService } from "@ngx-translate/core";
import { CropperAvatarDialogComponent } from "../../image-cropper/cropper-avatar/cropper-avatar-dialog.component";
export declare class UserProfileComponent implements OnInit, OnDestroy {
    private contactService;
    private userProfileService;
    private notification;
    private translate;
    tabContent: TemplateRef<ElementRef>;
    photoFrmElementRef: ElementRef;
    fileUpload: ElementRef;
    cropperAvatarDialog: CropperAvatarDialogComponent;
    profile: Contact;
    imageAvatarUrl: string;
    upload: boolean;
    defaultAvatarUrl: string;
    address: Address;
    private isAvatarExist;
    private profileTranslations;
    private readonly translateSubscription;
    constructor(contactService: GlobalContactService, userProfileService: UserProfileService, notification: NotificationService, translate: TranslateService);
    ngOnInit(): void;
    ngOnDestroy(): void;
    changeFileAvatar($event: any): void;
    onSelectFile($event: any): void;
    uploadImage($event: any): void;
    removeImage($event: any): void;
    updateBlankImage($event: any): void;
    private updateAvatar;
    onCropped(url: string): void;
}
