import { AfterViewInit, ElementRef, EventEmitter, OnDestroy, OnInit, TemplateRef } from '@angular/core';
import { Router } from "@angular/router";
import { AdminNavbarComponent } from "./navbar/navbar.component";
export declare class LayoutComponent implements OnInit, OnDestroy, AfterViewInit {
    private router;
    themeClass: string;
    menu: TemplateRef<ElementRef>;
    navbarItemTpl: TemplateRef<ElementRef>;
    profileItemTpl: TemplateRef<ElementRef>;
    navbarMenu: TemplateRef<ElementRef>;
    toolbar: TemplateRef<ElementRef>;
    homeRouterLink: string;
    appName: string;
    hideToggler: boolean;
    hideTogglerButton: boolean;
    visibleMenu: boolean;
    expandedMenu: boolean;
    expandedSlider: boolean;
    expandedMessageSlider: boolean;
    expandedAppSlider: boolean;
    expandedSocialSlider: boolean;
    expandedChatSlider: boolean;
    hideSearch: boolean;
    hideCompanyMenu: boolean;
    hideProfileMenu: boolean;
    hideBrandName: boolean;
    hideLogo: boolean;
    visibleOverlay: boolean;
    fullScreenLayout: boolean;
    fullLayoutWithUrls: Array<string>;
    routeChange: EventEmitter<{}>;
    onToggle: EventEmitter<boolean>;
    onClickLogo: EventEmitter<string>;
    visibleToolbar: boolean;
    visibleChatIcon: boolean;
    visibleMessageIcon: boolean;
    visibleAppIcon: boolean;
    visibleNoteIcon: boolean;
    private _router;
    navbarComponent: AdminNavbarComponent;
    constructor(router: Router);
    ngOnInit(): void;
    private onChangeUrl;
    ngAfterViewInit(): void;
    ngOnDestroy(): void;
    onToggleMenu($event: any): void;
    private updateSlider;
    onToggleMessageSlider($event: any): void;
    onToggleAppSlider($event: any): void;
    onToggleSocialSlider($event: any): void;
    onToggleNoteSlider($event: any): void;
    onCloseSlider($event: any): void;
    onClearMessage($event: any): void;
    onLoadMessage($event: any): void;
    clickLogo($event: any): void;
}
