import { ElementRef, OnInit } from '@angular/core';
import { SocialService } from '../../social.service';
import { AccentService, CacheStorageService } from 'inet-core';
export declare class ListUserComponent implements OnInit {
    private socialService;
    private accentService;
    private cacheStorage;
    placeholder: string;
    height: string;
    search: ElementRef;
    members: any[];
    selectMembers: any;
    showMembers: any;
    matchMembers: any;
    private _search;
    private _allEmployees;
    private _allFriends;
    constructor(socialService: SocialService, accentService: AccentService, cacheStorage: CacheStorageService);
    ngOnInit(): void;
    resetData(): void;
    focusInput(): void;
    onSearch(): void;
    onScroll(): void;
    addMember(member: any): void;
    removeMember(member: any): void;
    private _initMembers;
    private _addMember;
    private _sortMembers;
    private _hasMember;
}
