import { EventEmitter, ElementRef, OnInit } from '@angular/core';
import { SocialComment } from '../model/Comment';
import { AutoSizeDirective } from 'inet-core';
import { FileListItem } from 'inet-ui';
import { SocialService } from "../social.service";
import { ProgressComponent } from "../progress/progress.component";
export declare class CommentPostComponent implements OnInit {
    private socialService;
    placeholder: string;
    commentEdit: SocialComment;
    onCancel: EventEmitter<any>;
    onPost: EventEmitter<any>;
    messageEl: ElementRef;
    messageAutoSize: AutoSizeDirective;
    indicator: ProgressComponent;
    message: string;
    files: FileListItem[];
    removeFiles: FileListItem[];
    constructor(socialService: SocialService);
    ngOnInit(): void;
    enterPost(event: any): void;
    doPost(): void;
    doCancel(): void;
    getData(): any;
    editComment(comment: SocialComment): void;
    resetForm(): void;
    focusMessage(): void;
    private _getRemoveFiles;
    private _resizeInput;
}
