import { Address } from './address';
export declare class Organization {
    readonly uuid: string;
    readonly organId: string;
    createdDate: number;
    name: string;
    primaryEmail: string;
    type: string;
    address: string;
    officeAddress: Address;
    description: string;
    officeAddressStr: string;
    taxCode: string;
    foreignName: string;
    abbreviationName: string;
    website: string;
    primaryPhone: string;
    companySize: string;
    industry: string;
    legalRepName: string;
    legalRepCanonId: string;
    createdBy: string;
    logo: string;
    readonly ownerId: string;
    readonly memberOfId: string;
    readonly ownerShip: string;
    readonly region: string;
    readonly modifiedBy: string;
    readonly modifiedDate: number;
    banks: Array<any>;
    busAces: Array<any>;
    constructor();
}
