import { ElementRef, EventEmitter, OnDestroy, OnInit } from '@angular/core';
import { Location } from "@angular/common";
import { ActivatedRoute } from "@angular/router";
import { NotificationService } from "inet-core";
import { FormBuilder, FormGroup } from "@angular/forms";
import { TranslateService } from "@ngx-translate/core";
import { ReportTemplateService } from "../report-template.service";
export declare class ReportTemplateEditComponent implements OnInit, OnDestroy {
    private location;
    private fb;
    private notification;
    private service;
    private translate;
    private route;
    templateId: string;
    validForm: EventEmitter<boolean>;
    appName: string;
    appDesc: string;
    applicationList: any[];
    typeList: any[];
    moduleList: any[];
    versionList: {
        name: number;
        description: string;
    }[];
    templateFormGroup: FormGroup;
    attachments: any[];
    fileName: string;
    applicationParams: string;
    moduleParams: string;
    typeParams: string;
    private subRouter;
    private translateSubscription;
    private formTranslations;
    templateFormElementRef: ElementRef;
    constructor(location: Location, fb: FormBuilder, notification: NotificationService, service: ReportTemplateService, translate: TranslateService, route: ActivatedRoute);
    ngOnInit(): void;
    ngOnDestroy(): void;
    loadById(templateId: string): void;
    private initData;
    reset(): void;
    changeFile($event: any): void;
    clearForm(): void;
    private loadApplication;
    changeApps($event: any): void;
    private loadModules;
    changeModules($event: any): void;
    save(): void;
    initForm(): void;
    readonly uuid: import("@angular/forms/src/model").AbstractControl;
    readonly application: import("@angular/forms/src/model").AbstractControl;
    readonly module: import("@angular/forms/src/model").AbstractControl;
    readonly type: import("@angular/forms/src/model").AbstractControl;
    readonly name: import("@angular/forms/src/model").AbstractControl;
    readonly description: import("@angular/forms/src/model").AbstractControl;
    readonly version: import("@angular/forms/src/model").AbstractControl;
    readonly organId: import("@angular/forms/src/model").AbstractControl;
    readonly fileUpload: import("@angular/forms/src/model").AbstractControl;
    changeFormValid(): void;
}
