import { CalMode } from "./CalMode";
import { CalAttachment } from "./CalAttachment";
import { CalAttendee } from "./CalAttendee";
import { CalType } from "./CalType";
export interface CalEvent {
    uuid?: string;
    firmUUID?: string;
    firmName?: string;
    firmPrefix?: string;
    departID?: string;
    departName?: string;
    caldavRef?: string;
    mode?: CalMode;
    year?: number;
    month?: number;
    week?: number;
    day?: number;
    subject?: string;
    location?: string;
    category?: string;
    startTime?: number;
    toTime?: number;
    createTime?: number;
    updateTime?: number;
    attribute?: any;
    attachments?: CalAttachment[];
    reminderByEmail?: boolean;
    alertReminder?: boolean;
    contextID?: string;
    application?: string;
    groupID?: string;
    organId?: string;
    path?: string;
    mpath?: string;
    type?: CalType;
    members?: CalAttendee[];
    lstart?: number;
    until?: number;
    rrule?: string;
    summary?: string;
    title?: string;
    start?: any;
    end?: any;
    timeStr?: string;
    timeago?: string;
    memberStr?: string;
    hasVideo?: boolean;
    isCreator?: boolean;
    repeat?: CalRepeat;
    attendees?: any[];
    creator?: any;
    isCreate?: boolean;
    isPublish?: boolean;
    isCancel?: boolean;
    isSent?: boolean;
    isOther?: boolean;
    myAttendee?: CalAttendee;
}
export interface CalRepeat {
    rrmode?: string;
    wkdays?: string[];
    start?: number;
    until?: number;
}
