import { Member } from './Member';
import { Attachment } from './Attachment';
import { SocialMember } from './Config';
export declare class SocialActivity {
    activityID?: string;
    alias?: string;
    application?: string;
    contextID?: string;
    mpath?: string;
    path?: string;
    attachments?: Attachment[];
    avataUrl?: string;
    count?: number;
    fullname?: string;
    creator?: string;
    external?: boolean;
    firmContext?: string;
    likeCount?: number;
    likeStatus?: boolean;
    message?: string;
    organId?: string;
    policies?: Member[];
    pollAttached?: boolean;
    posted?: number;
    lastUpdate?: number;
    published?: boolean;
    type?: string;
    uuid?: string;
    comments?: any[];
    images?: any[];
    files?: any[];
    editing?: boolean;
    isCreator?: boolean;
    _policies?: SocialMember[];
    _policiesStr?: string;
    _displayMessage?: string;
    _openGraph?: any;
    _localNews?: any;
    _editable?: boolean;
    _localNewsPin?: boolean;
}
