import { OnInit, EventEmitter, OnDestroy } from '@angular/core';
import { FormBuilder, FormGroup } from "@angular/forms";
import { NotificationService } from "inet-core";
import { EmailTemplateService } from "../email-template.service";
import { TranslateService } from "@ngx-translate/core";
import { EmailTemplate } from "../email-template";
export declare class EmailTemplateEditComponent implements OnInit, OnDestroy {
    private fb;
    private notification;
    private translate;
    private emailTemplateService;
    email: EmailTemplate;
    emailTemplateForm: FormGroup;
    visibleProperty: boolean;
    emailId: string;
    emailParams: any[];
    editorConfig: {
        "editable": boolean;
        "spellcheck": boolean;
        "height": string;
        "minHeight": string;
        "width": string;
        "minWidth": string;
        "translate": string;
        "enableToolbar": boolean;
        "showToolbar": boolean;
        "placeholder": string;
        "imageEndPoint": string;
        "toolbar": string[][];
    };
    onValidate: EventEmitter<boolean>;
    onUpdate: EventEmitter<any>;
    onToggleProperty: EventEmitter<boolean>;
    private formChanged;
    private translateSubscription;
    private columnsTranslations;
    constructor(fb: FormBuilder, notification: NotificationService, translate: TranslateService, emailTemplateService: EmailTemplateService);
    ngOnInit(): void;
    ngOnDestroy(): void;
    initForm(): void;
    loadById(emailId: string): void;
    toggleProperty(): boolean;
    setData(emailTemplate: EmailTemplate): void;
    clearData(): void;
    setEditorPlaceholder(placeholderContent: string): void;
    private getData;
    update(): void;
}
