import { ElementRef, AfterViewInit, OnDestroy, OnInit } from '@angular/core';
import { SocialService } from '../social.service';
import { Policy, SocialMember } from '../model/Config';
import { AccentService } from 'inet-core';
import { SocialActivity } from "../model/Activity";
import { SocialComment } from "../model/Comment";
export declare class ShareMemberComponent implements OnInit, OnDestroy, AfterViewInit {
    private socialService;
    private accentService;
    shareModal: any;
    inputMember: ElementRef;
    contactList: ElementRef;
    companyMode: boolean;
    activity: SocialActivity | SocialComment;
    categories: SocialMember[];
    companyCategories: SocialMember[];
    communityCategories: SocialMember[];
    groups: SocialMember[];
    contacts: SocialMember[];
    members: SocialMember[];
    friends: SocialMember[];
    searchContacts: SocialMember[];
    selectContacts: SocialMember[];
    showMenu: boolean;
    displayIcon: string;
    display: string;
    policies: Policy[];
    customActive: boolean;
    private _matchContacts;
    private _params;
    private _modalShowObserver;
    constructor(socialService: SocialService, accentService: AccentService);
    ngOnInit(): void;
    ngOnDestroy(): void;
    ngAfterViewInit(): void;
    init(): void;
    setDefault(): void;
    setPolicies(members?: SocialMember[]): void;
    injectPolicies(params: any): any;
    selectMember(member: SocialMember): void;
    onCloseMenu(): void;
    openSelectCustom(): void;
    closeMenu(): void;
    openMenu(): void;
    searchMember(): void;
    addMember(member: SocialMember): void;
    removeMember(member: SocialMember): void;
    hasSelectedMember(member: SocialMember): boolean;
    getIndexMemberSelected(member: SocialMember): number;
    isOpening(): any;
    cancelChanges(e: any): void;
    saveChanges(e: any): void;
    onScrollContact(e: any): void;
    private _scrollTopModal;
    private _updateSelectContacts;
    private _resetActive;
    private _resetModal;
    private _loadContacts;
    private _hasContacts;
    private _sortMembers;
    private _indexKeyToSearch;
    private _createSocialMember;
    private _focusInputMember;
    private _setSearchKeyword;
    private _getSearchKeyword;
}
