import { EventEmitter, OnInit } from '@angular/core';
import { FormBuilder, FormGroup } from '@angular/forms';
import { TranslateService } from '@ngx-translate/core';
import { Location } from '@angular/common';
import { OrganizationService } from '../organization.service';
import { LocationService } from "../../common/location.service";
import { Organization } from "../../model/organization";
import { DictionaryService } from "../../common/dictionary.service";
export declare class OrganizationGeneralInformationComponent implements OnInit {
    private location;
    private orgService;
    private fb;
    private locationService;
    private dictionaryService;
    private translate;
    orgInfo: Organization;
    editable: boolean;
    orgInfoForm: FormGroup;
    link: string;
    langs: Array<string>;
    countries: Array<any>;
    provinces: Array<any>;
    districts: Array<any>;
    companySizeCodes: Array<any>;
    industries: Array<any>;
    private countryCode;
    private provinceCode;
    onValidate: EventEmitter<{}>;
    private formChanged;
    constructor(location: Location, orgService: OrganizationService, fb: FormBuilder, locationService: LocationService, dictionaryService: DictionaryService, translate: TranslateService);
    ngOnInit(): void;
    setData(org: Organization): void;
    getData(): Organization;
    private loadAddress;
    private loadProvinceByCountryCode;
    private loadDistrictByCode;
    onChangeCountry($event: any): void;
    onChangeProvince($event: any): void;
}
